### ISSUE TITLE
Python3 - runtests.sh uses Python2 variable

### ISSUE THREAD

**Issue by jflory7** [rodrigc/kernel-tests#2]
When running the script using Python3, it fails to run.

```
$ python3 runtests.sh
  File "runtests.sh", line 5
    date=$(date +%s)
         ^
SyntaxError: invalid syntax
```

**Comment by rodrigc** [comment]
Why did you run a Bash script *runtests.sh* with python3?

**Comment by jflory7** [comment]
D'oh. Not sure what I was thinking, must not have been paying close attention. Guess I should probably get some sleep. :stuck_out_tongue:
